# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000

remappings = [
  "forge-std-1.9.4/=dependencies/forge-std-1.9.4/",
  "@openzeppelin-contracts-5.1.0/=dependencies/@openzeppelin-contracts-5.1.0/",
]

[soldeer]
recursive_deps = true

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.1.0"
